version: '3'
services:
  postgres:
    ports:
      - "5433:5432"  # Maps container's port 5432 to host's port 5433

  webserver:
    volumes:
      - ${AIRFLOW_DBT_PROJECT_PATH}:/usr/local/airflow/dbt

  scheduler:
    volumes:
      - ${AIRFLOW_DBT_PROJECT_PATH}:/usr/local/airflow/dbt
